name: Final project tests
on: [push]
env:
  GO111MODULE: "on"

jobs:
  go_get:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: go get
        run: go mod tidy

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Unit tests
        run: go test -v -count=10 -race -timeout=1m ./...

  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: make lint
        run: make lint

      - name: make test
        run: make test
